[package]
name = "idea-discussion-master"
version = "0.5.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name="idea-discussion-master"
path="./src/main.rs"

[dependencies]
serde = {version = "1.0.130", features = ["derive"]}
serde_json = "1.0.66"
serenity = "0.10.9"
tokio = {version = "1.6.0", features = ["full"]}
reqwest = {version = "0.11.7", features = ["json"]}
chrono = "0.4.19"
regex = "1.5.4"
itertools = "0.10.1"
strum = { version = "0.21.0", features = ["derive"] }
test-case = "1.2.1"
mockall = "0.10.2"
cfg-if = "1.0.0"
futures = "0.3.18"
