[workspace]
members = [
  "crate-shared",
  "c-domain",
  "c-usecase",
  "c-infra",
  "c-presentation"
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0"
chrono = "0.4"
derive-new = "0.5"
futures = "0.3"
itertools = "0.10"
regex = "1.6"
strum = { version = "0.24", features = ["derive"] }
test-case = "2.2"
tokio = { version = "1.21", features = ["macros", "rt", "rt-multi-thread"] }
