[package]
name = "idea-discussion-master"
version = "0.5.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name="idea-discussion-master"
path="./src/main.rs"

[dependencies]
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
serenity = "0.10"
tokio = {version = "1.14", features = ["full"]}
reqwest = {version = "0.11", features = ["json"]}
chrono = "0.4"
regex = "1.5"
itertools = "0.10"
strum = { version = "0.23", features = ["derive"] }
test-case = "1.2"
mockall = "0.10"
cfg-if = "1.0"
futures = "0.3"
create-github-app-token = "2.0"
