name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  build_test_and_deploy:
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 1
      CARGO_TERM_COLOR: always
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # https://nnao45.hatenadiary.com/entry/2019/06/13/113332

      # IncrementalBuildが機能しないので、以下3ステップでファイルのタイムスタンプをgitから復元する
      # https://zenn.dev/kt3k/articles/d557cc874961ab
      - name: Install Python
        uses: actions/setup-python@v2
      - name: Install git-restore-mtime
        run: sudo apt-get update && sudo apt-get install git-restore-mtime -y
      - name: Restore mtime
        run: git restore-mtime

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./target
          key: cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --release
      - name: Run tests
        run: cargo test --release

      - run: |
          cd ./target/release/
          ls -la
