name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 1
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # IncrementalBuildが機能しないので、以下3ステップでファイルのタイムスタンプをgitから復元する
      # https://zenn.dev/kt3k/articles/d557cc874961ab
      - name: Install Python
        uses: actions/setup-python@v2
      - name: Install git-restore-mtime
        run: sudo apt-get update && sudo apt-get install git-restore-mtime -y
      - name: Restore mtime
        run: git restore-mtime

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            ${{ github.ref }}-${{ github.sha }}
            ${{ github.ref }}
            refs/head/main

      - name: Build
        run: cargo build --release
      - name: Run tests
        run: cargo test --release

      - name: Upload built artifacts
        uses: actions/upload-artifact@v2
        with:
          name: built_artifacts
          retention-days: 1
          path: ./target/release/

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Download built artifacts
        uses: actions/download-artifact@v2
        with:
          name: built_artifacts
      - run: ls -la
