name: Build, lint and test

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
      - "renovate.json"
      - ".env.example"
      - ".github/workflows/**"
      - "!.github/workflows/build-binary.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 0
    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1
      - name: Run Clippy
        uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
      - name: Run formatter
        run: cargo fmt --all -- --check

  test:
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 0
    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1
      - name: Run tests
        run: cargo test
