name: Build and push docker image
on: [push]
  # push:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Output image name
        id: image
        env:
          OWNER: ${{ github.repository_owner }}
        run: |
          NAME="ghcr.io/${OWNER,,}/idea-discussion-master"
          echo "::set-output name=name::$NAME"
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.image.outputs.name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
