name: hadolint with reviewdog

on:
  pull_request:
    branch: [main]

jobs:
  hadolint:
    name: Execute hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Execute hadolint
        uses: reviewdog/action-hadolint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          hadolint_ignore: DL3007 DL3059
