name: Lint Dockerfile
on:
  pull_request:
    paths:
      - "Dockerfile"
      - ".github/workflows/lint-dockerfile.yml"

jobs:
  hadolint:
    name: runner / hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: hadolint
        uses: reviewdog/action-hadolint@v1
        with:
          reporter: github-pr-review
          hadolint_ignore: DL3006 DL3021 DL3059
