name: Build and Publish Docker

on:
  pull_request:
    branch: [main]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      IMAGE: ghcr.io/lucky3028/idea-discussion-master
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: lucky3028
          password: ${{ secrets.GHCR_PAT }}

      - name: Prepare dummy
        run: |
          curl -s https://api.github.com/repos/Lucky3028/create-dummy-toml/releases/latest \
            | grep "browser_download_url" \
            | cut -d : -f 2,3 \
            | tr -d \" \
            | wget -qi -
          chmod u+x create_dummy_toml
          ./create_dummy_toml

      - name: Build builder image
        run: docker build --target builder --cache-from $IMAGE:builder -t $IMAGE:builder --build-arg BUILDKIT_INLINE_CACHE=1 .
      - name: Build image
        run: docker build --cache-from $IMAGE:builder --cache-from $IMAGE:latest -t $IMAGE:latest --build-arg BUILDKIT_INLINE_CACHE=1 .

      - name: Push image
        run: |
          docker push $IMAGE:builder &
          docker push $IMAGE:latest &
          wait

  scan_vululnerability:
    needs: build_and_deploy
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/lucky3028/idea-discussion-master
    steps:
      - name: Cache trivy DB
        uses: actions/cache@v2
        with:
          path: ~/.cache/trivy
          key: trivy-vulnerability-db

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: lucky3028
          password: ${{ secrets.GHCR_PAT }}

      - uses: lazy-actions/gitrivy@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ env.IMAGE }}:latest
          fail_on_vulnerabilities: false
          issue_title: Security Alert for executor image
