name: Build and Publish Docker

on:
  pull_request:
    branch: [main]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      IMAGE: ghcr.io/lucky3028/idea-discussion-master
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/bin/dummy-cargo-toml-creater
            ./target
          key: cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Mkdir target
        run: |
          if [ ! -d target ];then
            mkdir ./target
          fi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: lucky3028
          password: ${{ secrets.GHCR_PAT }}

      - name: Prepare dummy Cargo.toml & lock for build
        run: |
          cargo install dummy-cargo-toml-creater
          ~/.cargo/bin/dummy-cargo-toml-creater

      # IncrementalBuildが機能しないので、以下3ステップでファイルのタイムスタンプをgitから復元する
      # https://zenn.dev/kt3k/articles/d557cc874961ab
      - name: Install python
        uses: actions/setup-python@v2
      - name: Install git-restore-mtime
        run: sudo apt-get update && sudo apt-get install git-restore-mtime -y
      - name: restore mtime
        run: git restore-mtime

      - name: Build builder image
        run: docker build --target builder -t $IMAGE:builder --cache-from $IMAGE:builder --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg CARGO_INCREMENTAL=1 .
      - name: Build image
        run: docker build --cache-from $IMAGE:builder --cache-from $IMAGE:latest -t $IMAGE:latest --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg CARGO_INCREMENTAL=1 .

      - name: Push image
        run: |
          docker push $IMAGE:builder &
          docker push $IMAGE:latest &
          wait
