name: Build and Publish Docker

on:
  pull_request:
    branch: [main]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      IMAGE: ghcr.io/lucky3028/idea-discussion-master
    steps:
      - uses: actions/checkout@v2
      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: lucky3028
          password: ${{ secrets.GHCR_PAT }}
      - name: prepare dummy Cargo.toml & lock for build
        run: |
          cargo install dummy-cargo-toml-creater
          ~/.cargo/bin/dummy-cargo-toml-creater
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./target
          key: cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: build builder image
        run: docker build --target builder -t $IMAGE:builder --cache-from $IMAGE:builder \
                -v ~/.cargo/registry/:/usr/local/cargo/registry/ \
                -v ~/.cargo/git/:/usr/local/cargo/git/ \
                -v ./target/:/tmp/app/target/ \
                --build-arg BUILDKIT_INLINE_CACHE=1 .
      - name: build image
        run: docker build --cache-from $IMAGE:builder --cache-from $IMAGE:latest \
                -t $IMAGE:latest --build-arg BUILDKIT_INLINE_CACHE=1 .
      - name: push image
        run: |
          docker push $IMAGE:builder &
          docker push $IMAGE:latest &
          wait
