name: Build and Publish Docker

on:
  pull_request:
    branch: [main]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      IMAGE_OWNER: lucky3028
      IMAGE_NAME: idea-discussion-master
    steps:
      - uses: actions/checkout@v2

      - name: Set image name
        run: |
          echo "IMAGE=ghcr.io/${IMAGE_OWNER}/${IMAGE_NAME}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: lucky3028
          password: ${{ secrets.GHCR_PAT }}

      - name: Prepare dummy Cargo.toml & lock for build
        run: |
          cargo install dummy-cargo-toml-creater
          ~/.cargo/bin/dummy-cargo-toml-creater

      - name: Build builder image
        run: docker build --target builder -t $IMAGE:builder --cache-from $IMAGE:builder --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg CARGO_INCREMENTAL=1 .
      - name: Build image
        run: docker build --cache-from $IMAGE:builder --cache-from $IMAGE:latest -t $IMAGE:latest --build-arg BUILDKIT_INLINE_CACHE=1 --build-arg CARGO_INCREMENTAL=1 .

      - name: Push image
        run: |
          docker push $IMAGE:builder &
          docker push $IMAGE:latest &
          wait

      - uses: jcansdale/delete-untagged-images@master
        with:
          owner: ${IMAGE_OWNER}
          package: ${IMAGE_NAME}
          token: ${{ secrets.GHCR_PAT }}
